/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/users/{id}': {
    get: operations['getUser'];
    put: operations['updateUser'];
    delete: operations['deactivateUser'];
  };
  '/api/groups/{id}': {
    get: operations['getGroup'];
    put: operations['updateGroup'];
    delete: operations['deactivateGroup'];
  };
  '/api/courses/{id}': {
    get: operations['getCourse'];
    put: operations['updateCourse'];
    delete: operations['deactivateCourse'];
  };
  '/api/assignments/{id}': {
    get: operations['getAssignment'];
    put: operations['updateAssignment'];
    delete: operations['deactivateAssignment'];
  };
  '/api/webhooks/gitlab': {
    post: operations['handleGitLabWebhook'];
  };
  '/api/v1/users': {
    get: operations['listUsers'];
    post: operations['createUser'];
  };
  '/api/v1/teachers': {
    get: operations['listTeachers'];
    post: operations['createTeacher'];
  };
  '/api/v1/students': {
    get: operations['listStudents'];
    post: operations['createStudent'];
  };
  '/api/groups': {
    get: operations['listGroups'];
    post: operations['createGroup'];
  };
  '/api/groups/{id}/students/{studentId}': {
    post: operations['addStudent'];
    delete: operations['removeStudent'];
  };
  '/api/courses': {
    get: operations['listCourses'];
    post: operations['createCourse'];
  };
  '/api/courses/{id}/teachers/{teacherId}': {
    post: operations['addTeacher'];
    delete: operations['removeTeacher'];
  };
  '/api/courses/{id}/students/{studentId}': {
    post: operations['enrollStudent'];
    delete: operations['unenrollStudent'];
  };
  '/api/courses/{id}/groups/{groupId}': {
    post: operations['enrollGroup'];
    delete: operations['unenrollGroup'];
  };
  '/api/courses/{courseId}/assignments': {
    get: operations['listAssignments'];
    post: operations['createAssignment'];
  };
  '/api/compile/validate': {
    post: operations['validateCompilation'];
  };
  '/api/assignments/{assignmentId}/submissions': {
    get: operations['listByAssignment'];
    post: operations['createSubmission'];
  };
  '/api/assignments/{assignmentId}/compile': {
    post: operations['validateSubmissionCompilation'];
  };
  '/api/v1/teachers/{id}': {
    get: operations['getTeacher'];
    delete: operations['deleteTeacher'];
  };
  '/api/v1/students/{id}': {
    get: operations['getStudent'];
    delete: operations['deleteStudent'];
  };
  '/api/submissions/{submissionId}/attempts': {
    get: operations['listAttempts'];
  };
  '/api/submissions/{id}': {
    get: operations['getSubmission'];
  };
  '/api/submissions/{id}/status': {
    get: operations['getStatus'];
  };
  '/api/groups/{id}/students': {
    get: operations['listStudents_1'];
  };
  '/api/courses/{id}/teachers': {
    get: operations['listTeachers_1'];
  };
  '/api/courses/{id}/students': {
    get: operations['listStudents_2'];
  };
  '/api/attempts/{attemptId}/status': {
    get: operations['getAttemptStatus'];
  };
  '/api/assignments/{assignmentId}/submissions/my': {
    get: operations['getMySubmission'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    UpdateUserRequest: {
      firstName: string;
      lastName: string;
      phone?: string;
      /** Format: date */
      dateOfBirth?: string;
      isActive?: boolean;
    };
    UserResponse: {
      /** Format: int64 */
      id?: number;
      email?: string;
      firstName?: string;
      lastName?: string;
      phone?: string;
      /** Format: date */
      dateOfBirth?: string;
      /** @enum {string} */
      role?: 'STUDENT' | 'TEACHER' | 'ADMIN';
      isActive?: boolean;
      /** Format: date-time */
      createdAt?: string;
    };
    UpdateGroupRequest: {
      code: string;
      faculty?: string;
      speciality?: string;
      /** Format: int32 */
      yearOfCreation: number;
    };
    GroupResponse: {
      /** Format: int64 */
      id?: number;
      code?: string;
      faculty?: string;
      speciality?: string;
      /** Format: int32 */
      yearOfCreation?: number;
      isActive?: boolean;
      /** Format: date-time */
      createdAt?: string;
    };
    UpdateCourseRequest: {
      name: string;
      description?: string;
      /** Format: int32 */
      academicYear: number;
      /** Format: int32 */
      semester: number;
    };
    CourseResponse: {
      /** Format: int64 */
      id?: number;
      name?: string;
      description?: string;
      /** Format: int32 */
      academicYear?: number;
      /** Format: int32 */
      semester?: number;
      isActive?: boolean;
      /** Format: date-time */
      createdAt?: string;
    };
    ProgrammingTaskDetails: {
      /** @enum {string} */
      language: 'C' | 'CPP';
      /** @enum {string} */
      testMode?: 'IO' | 'UNIT_TEST';
      ciConfigTemplate?: string;
      functionSignature?: string;
      testFileContent?: string;
      testCases?: components['schemas']['TestCaseDetails'][];
    };
    TestCaseDetails: {
      name: string;
      /** @enum {string} */
      testType: 'IO' | 'EXCEPTION';
      input?: string;
      expectedOutput?: string;
    };
    UpdateAssignmentRequest: {
      title: string;
      description?: string;
      /** Format: int32 */
      maxScore: number;
      /** Format: date-time */
      deadline?: string;
      programmingTask?: components['schemas']['ProgrammingTaskDetails'];
    };
    AssignmentResponse: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      courseId?: number;
      title?: string;
      description?: string;
      /** Format: int32 */
      maxScore?: number;
      /** Format: date-time */
      deadline?: string;
      isActive?: boolean;
      /** Format: int64 */
      createdBy?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      programmingTask?: components['schemas']['ProgrammingTaskDetails'];
    };
    GitLabWebhookPayload: {
      object_kind?: string;
      object_attributes?: components['schemas']['PipelineAttributes'];
      project?: components['schemas']['Project'];
    };
    PipelineAttributes: {
      /** Format: int32 */
      id?: number;
      status?: string;
      ref?: string;
    };
    Project: {
      /** Format: int32 */
      id?: number;
      name?: string;
    };
    CreateUserRequest: {
      /** Format: email */
      email: string;
      firstName: string;
      lastName: string;
      phone?: string;
      /** Format: date */
      dateOfBirth?: string;
      /** @enum {string} */
      role: 'STUDENT' | 'TEACHER' | 'ADMIN';
    };
    CreateTeacherRequest: {
      /** Format: int64 */
      userId: number;
      department?: string;
      academicDegree?: string;
    };
    TeacherResponse: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      userId?: number;
      firstName?: string;
      lastName?: string;
      email?: string;
      department?: string;
      academicDegree?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    CreateStudentRequest: {
      /** Format: int64 */
      userId: number;
    };
    StudentResponse: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      userId?: number;
      firstName?: string;
      lastName?: string;
      email?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: int64 */
      groupId?: number;
      groupCode?: string;
    };
    CreateGroupRequest: {
      code: string;
      faculty?: string;
      speciality?: string;
      /** Format: int32 */
      yearOfCreation: number;
    };
    GroupStudentResponse: {
      /** Format: int64 */
      studentId?: number;
      firstName?: string;
      lastName?: string;
      email?: string;
      /** Format: date-time */
      enrolledAt?: string;
    };
    CreateCourseRequest: {
      name: string;
      description?: string;
      /** Format: int32 */
      academicYear: number;
      /** Format: int32 */
      semester: number;
    };
    CourseTeacherResponse: {
      /** Format: int64 */
      teacherId?: number;
      firstName?: string;
      lastName?: string;
      email?: string;
      role?: string;
    };
    EnrolledStudentResponse: {
      /** Format: int64 */
      studentId?: number;
      firstName?: string;
      lastName?: string;
      email?: string;
      /** Format: date-time */
      enrolledAt?: string;
      status?: string;
      /** Format: int64 */
      groupId?: number;
      groupCode?: string;
    };
    CreateAssignmentRequest: {
      title: string;
      description?: string;
      /** Format: int32 */
      maxScore?: number;
      /** Format: date-time */
      deadline?: string;
      programmingTask?: components['schemas']['ProgrammingTaskDetails'];
    };
    CompileRequest: {
      solutionCode: string;
      testFileContent?: string;
    };
    CompileResponse: {
      success?: boolean;
      output?: string;
    };
    CreateSubmissionRequest: {
      codeContent?: string;
    };
    AttemptResponse: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      submissionId?: number;
      /** Format: int32 */
      attemptNumber?: number;
      /** @enum {string} */
      status?: 'PENDING' | 'RUNNING' | 'PASSED' | 'FAILED' | 'ERROR';
      /** Format: int32 */
      score?: number;
      codeContent?: string;
      /** Format: int64 */
      gitlabPipelineId?: number;
      pipelineOutput?: string;
      /** Format: date-time */
      submittedAt?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    SubmissionResponse: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      assignmentId?: number;
      /** Format: int64 */
      studentId?: number;
      studentEmail?: string;
      /** @enum {string} */
      status?: 'PENDING' | 'RUNNING' | 'PASSED' | 'FAILED' | 'ERROR';
      /** Format: int32 */
      score?: number;
      /** Format: int32 */
      bestScore?: number;
      /** Format: int32 */
      attemptCount?: number;
      /** Format: int64 */
      latestAttemptId?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    SubmissionStatusResponse: {
      /** Format: int64 */
      id?: number;
      /** @enum {string} */
      status?: 'PENDING' | 'RUNNING' | 'PASSED' | 'FAILED' | 'ERROR';
      /** Format: int32 */
      score?: number;
      /** Format: int32 */
      bestScore?: number;
      /** Format: int64 */
      latestAttemptId?: number;
    };
    CourseDetailResponse: {
      /** Format: int64 */
      id?: number;
      name?: string;
      description?: string;
      /** Format: int32 */
      academicYear?: number;
      /** Format: int32 */
      semester?: number;
      isActive?: boolean;
      /** Format: date-time */
      createdAt?: string;
      teachers?: components['schemas']['CourseTeacherResponse'][];
      students?: components['schemas']['EnrolledStudentResponse'][];
      assignments?: components['schemas']['AssignmentResponse'][];
    };
    AttemptStatusResponse: {
      /** Format: int64 */
      attemptId?: number;
      /** Format: int32 */
      attemptNumber?: number;
      /** @enum {string} */
      status?: 'PENDING' | 'RUNNING' | 'PASSED' | 'FAILED' | 'ERROR';
      /** Format: int32 */
      score?: number;
      pipelineOutput?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  getUser: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['UserResponse'];
        };
      };
    };
  };
  updateUser: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['UserResponse'];
        };
      };
    };
  };
  deactivateUser: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  getGroup: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['GroupResponse'];
        };
      };
    };
  };
  updateGroup: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateGroupRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['GroupResponse'];
        };
      };
    };
  };
  deactivateGroup: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  getCourse: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['CourseDetailResponse'];
        };
      };
    };
  };
  updateCourse: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCourseRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['CourseResponse'];
        };
      };
    };
  };
  deactivateCourse: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  getAssignment: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['AssignmentResponse'];
        };
      };
    };
  };
  updateAssignment: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAssignmentRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['AssignmentResponse'];
        };
      };
    };
  };
  deactivateAssignment: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  handleGitLabWebhook: {
    parameters: {
      header: {
        'X-Gitlab-Token': string;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GitLabWebhookPayload'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  listUsers: {
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['UserResponse'][];
        };
      };
    };
  };
  createUser: {
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['UserResponse'];
        };
      };
    };
  };
  listTeachers: {
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['TeacherResponse'][];
        };
      };
    };
  };
  createTeacher: {
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTeacherRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['TeacherResponse'];
        };
      };
    };
  };
  listStudents: {
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['StudentResponse'][];
        };
      };
    };
  };
  createStudent: {
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateStudentRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['StudentResponse'];
        };
      };
    };
  };
  listGroups: {
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['GroupResponse'][];
        };
      };
    };
  };
  createGroup: {
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateGroupRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['GroupResponse'];
        };
      };
    };
  };
  addStudent: {
    parameters: {
      path: {
        id: number;
        studentId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['GroupStudentResponse'];
        };
      };
    };
  };
  removeStudent: {
    parameters: {
      path: {
        id: number;
        studentId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  listCourses: {
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['CourseResponse'][];
        };
      };
    };
  };
  createCourse: {
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCourseRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['CourseResponse'];
        };
      };
    };
  };
  addTeacher: {
    parameters: {
      path: {
        id: number;
        teacherId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['CourseTeacherResponse'];
        };
      };
    };
  };
  removeTeacher: {
    parameters: {
      path: {
        id: number;
        teacherId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  enrollStudent: {
    parameters: {
      path: {
        id: number;
        studentId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['EnrolledStudentResponse'];
        };
      };
    };
  };
  unenrollStudent: {
    parameters: {
      path: {
        id: number;
        studentId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  enrollGroup: {
    parameters: {
      path: {
        id: number;
        groupId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['EnrolledStudentResponse'][];
        };
      };
    };
  };
  unenrollGroup: {
    parameters: {
      path: {
        id: number;
        groupId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': number[];
        };
      };
    };
  };
  listAssignments: {
    parameters: {
      path: {
        courseId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['AssignmentResponse'][];
        };
      };
    };
  };
  createAssignment: {
    parameters: {
      path: {
        courseId: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateAssignmentRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['AssignmentResponse'];
        };
      };
    };
  };
  validateCompilation: {
    requestBody: {
      content: {
        'application/json': components['schemas']['CompileRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['CompileResponse'];
        };
      };
    };
  };
  listByAssignment: {
    parameters: {
      path: {
        assignmentId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['SubmissionResponse'][];
        };
      };
    };
  };
  createSubmission: {
    parameters: {
      path: {
        assignmentId: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSubmissionRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['AttemptResponse'];
        };
      };
    };
  };
  validateSubmissionCompilation: {
    parameters: {
      path: {
        assignmentId: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CompileRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['CompileResponse'];
        };
      };
    };
  };
  getTeacher: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['TeacherResponse'];
        };
      };
    };
  };
  deleteTeacher: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  getStudent: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['StudentResponse'];
        };
      };
    };
  };
  deleteStudent: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  listAttempts: {
    parameters: {
      path: {
        submissionId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['AttemptResponse'][];
        };
      };
    };
  };
  getSubmission: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['SubmissionResponse'];
        };
      };
    };
  };
  getStatus: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['SubmissionStatusResponse'];
        };
      };
    };
  };
  listStudents_1: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['GroupStudentResponse'][];
        };
      };
    };
  };
  listTeachers_1: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['CourseTeacherResponse'][];
        };
      };
    };
  };
  listStudents_2: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['EnrolledStudentResponse'][];
        };
      };
    };
  };
  getAttemptStatus: {
    parameters: {
      path: {
        attemptId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['AttemptStatusResponse'];
        };
      };
    };
  };
  getMySubmission: {
    parameters: {
      path: {
        assignmentId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          '*/*': components['schemas']['SubmissionResponse'];
        };
      };
    };
  };
}
